### ISSUE TITLE
Make the Google API Key user specific

### ISSUE THREAD

**Issue by julianhofmann** [brrrrrrrt/brt_videourlreplace#2] opened 2018-01-23 16:20 UTC
Currently, there's a hardcoded key for use of Google/Youtube API in Classes/class.tx_brtvideourlreplace.php. This should be a user specific one.

**Comment by brrrrrrrt** [comment] 2018-01-23 19:10
you are absolutly correct, i will add a constant

**Comment by brrrrrrrt** [comment] 2018-01-23 21:55
fixed in latest release (v1.2.3)

**Closed by brrrrrrrt** 2018-01-23 21:55 UTC

**Comment by julianhofmann** [comment] 2018-01-24 10:18
Just tested, but $googleApiKey stays empty, due to an empty flatSetup array :-(

My minimal TS-template looks like this (as Static Templates are included: FSC, brt_videourlreplace):
![screenshot-localhost-2018-01-24-11-08-42](https://user-images.githubusercontent.com/25646388/35326805-1c6b158a-00f8-11e8-919a-88b190789689.png)
_Tested with TYPO3 8.7.9, PHP 7.2_

Maybe, reading out the key from setup_constants could solve this:
`$GLOBALS['TSFE']->tmpl->setup_constants['plugin.']['brt_videourl_replace.']['googleApiKey']`

**Comment by brrrrrrrt** [comment] 2018-01-24 14:26
hmm, that's strange, i was not able to reproduce this error, also  TYPO3 8.7.9 and PHP 7.2.1

**Comment by julianhofmann** [comment] 2018-01-24 14:52
Took me some tries to reproduce it again. Seems only a problem on non-cached pages (like &no_cache=1 or some dev-settings).

**Comment by brrrrrrrt** [comment] 2018-01-24 15:00
ok, i will look for a reliable way to read the constants, maybe ConfigurationManager or something like that.

what dev-settings do you think are the cause? just disabling the cache does not break it as it seems.

**Comment by julianhofmann** [comment] 2018-01-24 15:12
`&no_cache=1 ` is enough.

Can reproduce it:
- Clear caches
- call page (flatSetup is filled), doesn't matter if with/without `&no_cache=1`
- call the page again - with `&no_cache=1`

So, maybe it's an edge case not blocking most real use cases.

**Comment by brrrrrrrt** [comment] 2018-01-24 15:44
well, i am still "overchallenged" by the TYPO3 documentation, still have not found the perfect official way to access constants. maybe it is not "officially" supported to fetch it via flatSetup?

one way i could think of is to use:
`$this->configurationManager = GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Configuration\\ConfigurationManager');
$settings = $this->configurationManager->getConfiguration(\TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
`
but this would mean to that the constants have to be "moved" so the setup.

**Comment by julianhofmann** [comment] 2018-01-24 15:56
I'm not sure, but directly access TS constants is not a common way. "normally" you're using TS setup.
There are many example, where constants are simply "moved" to setup (e.g. storagePid, templateRootPath and so on). It _would_ be possible to access the constants directly, but the core (or extbase) always uses the way via setup.

Have searched for details about the behaviour of `flatSetup` yesterday, too :-(

**Comment by brrrrrrrt** [comment] 2018-01-24 16:11
yes, maybe it's just a bug that the constants appear in flatsetup :) 

sadly i cannot reproduce the buggy behavior also with diabled cache.

can you see if flatSetup is completley empty, or is it just missing the constants?

**Comment by brrrrrrrt** [comment] 2018-01-24 16:27
just tested: $GLOBALS['TSFE']->tmpl->setup_constants returns nothing.

you could also try to add this to your setup, maybe it helps with your "edge case":

plugin.brt_videourl_replace {
    thumbnail = {$plugin.brt_videourl_replace.thumbnail.disable}
    disableSSL = {$plugin.brt_videourl_replace.disableSSL}
    googleApiKey = {$plugin.brt_videourl_replace.googleApiKey}
}

i am just testing this together with $GLOBALS['TSFE']->tmpl->setup, maybe this should be the way to go anyway

**Comment by brrrrrrrt** [comment] 2018-01-24 17:54
just pushed 1.2.4-dev to master, which gets the values from setup instead of constants
